const express = require('express');
const router = express.Router();
const authRoutes = require('./auth');
const subscriptionRoutes = require('./subscription');
const profileRoutes = require('./profile');
const adminRoutes = require('./admin');
const auditRoutes = require('./audit');
const workoutPlanRoutes = require('./workoutPlans');
const workoutTemplateRoutes = require('./workoutTemplates');
const notificationRoutes = require('./notifications');
const exerciseProgressRoutes = require('./exerciseProgress');
const schedulerRoutes = require('./scheduler');
const dietProgressRoutes = require('./dietProgress');
const dietPlanStatsRoutes = require('./dietPlanStats');
const dietPlansRoutes = require('./dietPlans');
const musclesRoutes = require('./muscles');
const nutritionRoutes = require('./nutrition');
const exercisesRoutes = require('./exercises');
const usersRoutes = require('./users');
const doctorsRoutes = require('./doctors');

router.use('/auth', authRoutes);
router.use('/subscription', subscriptionRoutes);
router.use('/profile', profileRoutes);
router.use('/admin', adminRoutes);
router.use('/audit', auditRoutes);
router.use('/workout-plans', workoutPlanRoutes);
router.use('/workout-templates', workoutTemplateRoutes);
router.use('/notifications', notificationRoutes);
router.use('/exercise-progress', exerciseProgressRoutes);
router.use('/scheduler', schedulerRoutes);
router.use('/progress', dietProgressRoutes);
router.use('/diet-plans', dietPlansRoutes);
router.use('/diet-plans', dietPlanStatsRoutes);
router.use('/muscles', musclesRoutes);
router.use('/nutrition', nutritionRoutes);
router.use('/exercises', exercisesRoutes);
router.use('/users', usersRoutes);
router.use('/doctors', doctorsRoutes);

module.exports = router;
