const express = require('express');
const router = express.Router();
const authRoutes = require('./auth');
const subscriptionRoutes = require('./subscription');
const profileRoutes = require('./profile');
const adminRoutes = require('./admin');
const auditRoutes = require('./audit');
const workoutPlanRoutes = require('./workoutPlans');
const workoutTemplateRoutes = require('./workoutTemplates');
const notificationRoutes = require('./notifications');
const exerciseProgressRoutes = require('./exerciseProgress');
const schedulerRoutes = require('./scheduler');
const dietProgressRoutes = require('./dietProgress');
const dietPlanStatsRoutes = require('./dietPlanStats');
const dietPlansRoutes = require('./dietPlans');

router.use('/auth', authRoutes);
router.use('/subscription', subscriptionRoutes);
router.use('/profile', profileRoutes);
router.use('/admin', adminRoutes);
router.use('/audit', auditRoutes);
router.use('/workout-plans', workoutPlanRoutes);
router.use('/workout-templates', workoutTemplateRoutes);
router.use('/notifications', notificationRoutes);
router.use('/exercise-progress', exerciseProgressRoutes);
router.use('/scheduler', schedulerRoutes);
router.use('/progress', dietProgressRoutes);
router.use('/diet-plans', dietPlansRoutes);
router.use('/diet-plans', dietPlanStatsRoutes);

module.exports = router;
